# Generated by Django 6.0.3 on 2026-03-21 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='ID_Cliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('n_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'dbo.Cliente',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(db_column='ID_Factura', primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dbo.Factura',
            },
        ),
        migrations.CreateModel(
            name='Operativo',
            fields=[
                ('id_operativo', models.AutoField(db_column='ID_Operativo', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dbo.Operativo',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.AutoField(db_column='ID_Personal', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('n_telefonico', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'dbo.Personal',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(db_column='ID_Servicio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'dbo.Servicio',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(db_column='ID_Cita', primary_key=True, serialize=False)),
                ('fechahora', models.DateTimeField(db_column='FechaHora')),
                ('cliente', models.ForeignKey(db_column='ID_Cliente', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.cliente')),
                ('operativo', models.ForeignKey(blank=True, db_column='ID_Operativo', null=True, on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.operativo')),
            ],
            options={
                'db_table': 'dbo.Citas',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(db_column='ID_Estado', primary_key=True, serialize=False)),
                ('abierta', models.BooleanField(default=False)),
                ('cerrada', models.BooleanField(default=False)),
                ('pendiente', models.BooleanField(default=False)),
                ('cita', models.ForeignKey(db_column='ID_Cita', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.cita')),
            ],
            options={
                'db_table': 'dbo.Estado',
            },
        ),
        migrations.CreateModel(
            name='ExpedienteClinico',
            fields=[
                ('id_expediente', models.AutoField(db_column='ID_Expediente', primary_key=True, serialize=False)),
                ('nombre_medico', models.CharField(blank=True, max_length=100, null=True)),
                ('progreso', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_de_atencion', models.DateField(blank=True, null=True)),
                ('tratamiento', models.CharField(blank=True, max_length=200, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=200, null=True)),
                ('cliente', models.ForeignKey(db_column='ID_Cliente', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.cliente')),
                ('operativo', models.ForeignKey(db_column='ID_Operativo', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.operativo')),
            ],
            options={
                'db_table': 'dbo.ExpedienteClinico',
            },
        ),
        migrations.AddField(
            model_name='operativo',
            name='personal',
            field=models.ForeignKey(db_column='ID_Personal', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.personal'),
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id_administrativo', models.AutoField(db_column='ID_Administrativo', primary_key=True, serialize=False)),
                ('personal', models.ForeignKey(db_column='ID_Personal', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.personal')),
            ],
            options={
                'db_table': 'dbo.Administrativo',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.AutoField(db_column='ID_Registro', primary_key=True, serialize=False)),
                ('ingreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sueldos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('administrativo', models.ForeignKey(db_column='ID_Administrativo', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.administrativo')),
            ],
            options={
                'db_table': 'dbo.Registro',
            },
        ),
        migrations.CreateModel(
            name='PagoDeServicios',
            fields=[
                ('id_pago', models.AutoField(db_column='ID_Pago', primary_key=True, serialize=False)),
                ('agua', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('luz', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('internet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registro', models.ForeignKey(db_column='ID_Registro', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.registro')),
            ],
            options={
                'db_table': 'dbo.PagoDeServicios',
            },
        ),
        migrations.CreateModel(
            name='CitaServicio',
            fields=[
                ('id_citaservicio', models.AutoField(db_column='ID_CitaServicio', primary_key=True, serialize=False)),
                ('cita', models.ForeignKey(db_column='ID_Cita', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.cita')),
                ('servicio', models.ForeignKey(db_column='ID_Servicio', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.servicio')),
            ],
            options={
                'db_table': 'dbo.CitaServicio',
                'unique_together': {('cita', 'servicio')},
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(through='CasaDrScholl_app.CitaServicio', to='CasaDrScholl_app.servicio'),
        ),
        migrations.CreateModel(
            name='ServicioFactura',
            fields=[
                ('id_serviciofactura', models.AutoField(db_column='ID_ServicioFactura', primary_key=True, serialize=False)),
                ('costos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(db_column='ID_Factura', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.factura')),
                ('servicio', models.ForeignKey(db_column='ID_Servicio', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.servicio')),
            ],
            options={
                'db_table': 'dbo.Serviciofactura',
            },
        ),
        migrations.CreateModel(
            name='ServicioOperativo',
            fields=[
                ('id_serviciooperativo', models.AutoField(db_column='ID_ServicioOperativo', primary_key=True, serialize=False)),
                ('operativo', models.ForeignKey(db_column='ID_Operativo', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.operativo')),
                ('servicio', models.ForeignKey(db_column='ID_Servicio', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.servicio')),
            ],
            options={
                'db_table': 'dbo.ServicioOperativo',
            },
        ),
    ]
