# Generated by Django 5.2.8 on 2025-11-28 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasaDrScholl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dbo.Administrativo',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(db_column='FechaHora')),
            ],
            options={
                'db_table': 'dbo.Citas',
            },
        ),
        migrations.CreateModel(
            name='CitaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('n_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'dbo.Cliente',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta', models.BooleanField(default=False)),
                ('cerrada', models.BooleanField(default=False)),
                ('pendiente', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dbo.Estado',
            },
        ),
        migrations.CreateModel(
            name='ExpedienteClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.CharField(blank=True, max_length=100, null=True)),
                ('progreso', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_de_atencion', models.DateField(blank=True, null=True)),
                ('tratamiento', models.CharField(blank=True, max_length=200, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=200, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.cliente')),
            ],
            options={
                'db_table': 'dbo.ExpedienteClinico',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dbo.Factura',
            },
        ),
        migrations.CreateModel(
            name='Operativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dbo.Operativo',
            },
        ),
        migrations.CreateModel(
            name='PagoDeServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('luz', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('internet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'dbo.PagoDeServicios',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('n_telefonico', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sueldos', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'dbo.Registro',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'dbo.Servicio',
            },
        ),
        migrations.CreateModel(
            name='ServicioFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.factura')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.servicio')),
            ],
            options={
                'db_table': 'dbo.Serviciofactura',
            },
        ),
        migrations.CreateModel(
            name='ServicioOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dbo.ServicioOperativo',
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(db_column='ID_Cliente', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.cliente'),
        ),
        migrations.AddField(
            model_name='estado',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.cita'),
        ),
        migrations.AddField(
            model_name='expedienteclinico',
            name='operativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.operativo'),
        ),
        migrations.AddField(
            model_name='operativo',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.personal'),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.personal'),
        ),
        migrations.AddField(
            model_name='registro',
            name='administrativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.administrativo'),
        ),
        migrations.AddField(
            model_name='pagodeservicios',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.registro'),
        ),
        migrations.AddField(
            model_name='citaservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.servicio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(through='CasaDrScholl_app.CitaServicio', to='CasaDrScholl_app.servicio'),
        ),
        migrations.AddField(
            model_name='serviciooperativo',
            name='operativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.operativo'),
        ),
        migrations.AddField(
            model_name='serviciooperativo',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.servicio'),
        ),
        migrations.AlterUniqueTogether(
            name='citaservicio',
            unique_together={('cita', 'servicio')},
        ),
    ]
