# Generated by Django 5.2.8 on 2025-11-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasaDrScholl_app', '0002_administrativo_cita_citaservicio_cliente_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='id',
        ),
        migrations.RemoveField(
            model_name='citaservicio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='id',
        ),
        migrations.RemoveField(
            model_name='expedienteclinico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id',
        ),
        migrations.RemoveField(
            model_name='operativo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pagodeservicios',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='id',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='serviciofactura',
            name='id',
        ),
        migrations.RemoveField(
            model_name='serviciooperativo',
            name='id',
        ),
        migrations.AddField(
            model_name='administrativo',
            name='id_administrativo',
            field=models.AutoField(db_column='ID_Administrativo', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_cita',
            field=models.AutoField(db_column='ID_Cita', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='citaservicio',
            name='id_citaservicio',
            field=models.AutoField(db_column='ID_CitaServicio', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='estado',
            name='id_estado',
            field=models.AutoField(db_column='ID_Estado', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='expedienteclinico',
            name='id_expediente',
            field=models.AutoField(db_column='ID_Expediente', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_factura',
            field=models.AutoField(db_column='ID_Factura', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='operativo',
            name='id_operativo',
            field=models.AutoField(db_column='ID_Operativo', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pagodeservicios',
            name='id_pago',
            field=models.AutoField(db_column='ID_Pago', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='id_personal',
            field=models.AutoField(db_column='ID_Personal', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='registro',
            name='id_registro',
            field=models.AutoField(db_column='ID_Registro', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_servicio',
            field=models.AutoField(db_column='ID_Servicio', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='serviciofactura',
            name='id_serviciofactura',
            field=models.AutoField(db_column='ID_ServicioFactura', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='serviciooperativo',
            name='id_serviciooperativo',
            field=models.AutoField(db_column='ID_ServicioOperativo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='personal',
            field=models.ForeignKey(db_column='ID_Personal', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.personal'),
        ),
        migrations.AlterField(
            model_name='citaservicio',
            name='cita',
            field=models.ForeignKey(db_column='ID_Cita', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.cita'),
        ),
        migrations.AlterField(
            model_name='citaservicio',
            name='servicio',
            field=models.ForeignKey(db_column='ID_Servicio', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.servicio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.AutoField(db_column='ID_Cliente', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estado',
            name='cita',
            field=models.ForeignKey(db_column='ID_Cita', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.cita'),
        ),
        migrations.AlterField(
            model_name='expedienteclinico',
            name='cliente',
            field=models.ForeignKey(db_column='ID_Cliente', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.cliente'),
        ),
        migrations.AlterField(
            model_name='expedienteclinico',
            name='operativo',
            field=models.ForeignKey(db_column='ID_Operativo', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.operativo'),
        ),
        migrations.AlterField(
            model_name='operativo',
            name='personal',
            field=models.ForeignKey(db_column='ID_Personal', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.personal'),
        ),
        migrations.AlterField(
            model_name='pagodeservicios',
            name='registro',
            field=models.ForeignKey(db_column='ID_Registro', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.registro'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='administrativo',
            field=models.ForeignKey(db_column='ID_Administrativo', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.administrativo'),
        ),
        migrations.AlterField(
            model_name='serviciofactura',
            name='factura',
            field=models.ForeignKey(db_column='ID_Factura', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.factura'),
        ),
        migrations.AlterField(
            model_name='serviciofactura',
            name='servicio',
            field=models.ForeignKey(db_column='ID_Servicio', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.servicio'),
        ),
        migrations.AlterField(
            model_name='serviciooperativo',
            name='operativo',
            field=models.ForeignKey(db_column='ID_Operativo', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.operativo'),
        ),
        migrations.AlterField(
            model_name='serviciooperativo',
            name='servicio',
            field=models.ForeignKey(db_column='ID_Servicio', on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.servicio'),
        ),
        migrations.AlterModelTable(
            name='citaservicio',
            table='dbo.CitaServicio',
        ),
        migrations.AlterModelTable(
            name='personal',
            table='dbo.Personal',
        ),
    ]
