# Generated by Django 5.2.8 on 2025-12-04 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasaDrScholl_app', '0003_remove_administrativo_id_remove_cita_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='operativo',
            field=models.ForeignKey(db_column='ID_Operativo', default=1, on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.operativo'),
            preserve_default=False,
        ),
    ]
