# Generated by Django 5.2.8 on 2025-12-04 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasaDrScholl_app', '0004_cita_operativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='operativo',
            field=models.ForeignKey(blank=True, db_column='ID_Operativo', null=True, on_delete=django.db.models.deletion.CASCADE, to='CasaDrScholl_app.operativo'),
        ),
    ]
