# Generated by Django 6.0.3 on 2026-03-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasaDrScholl_app', '0005_alter_cita_operativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
