# Generated by Django 6.0.3 on 2026-03-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CasaDrScholl_app', '0007_personal_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='citaservicio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='expedienteclinico',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='operativo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pagodeservicios',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registro',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='serviciofactura',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='serviciooperativo',
            options={'managed': False},
        ),
    ]
