# Generated by Django 6.0.3 on 2026-03-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CasaDrScholl_app', '0008_alter_administrativo_options_alter_cita_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrativo',
            table='Administrativo',
        ),
        migrations.AlterModelTable(
            name='cita',
            table='Citas',
        ),
        migrations.AlterModelTable(
            name='citaservicio',
            table='CitaServicio',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
        migrations.AlterModelTable(
            name='estado',
            table='Estado',
        ),
        migrations.AlterModelTable(
            name='expedienteclinico',
            table='ExpedienteClinico',
        ),
        migrations.AlterModelTable(
            name='factura',
            table='Factura',
        ),
        migrations.AlterModelTable(
            name='operativo',
            table='Operativo',
        ),
        migrations.AlterModelTable(
            name='pagodeservicios',
            table='PagoDeServicios',
        ),
        migrations.AlterModelTable(
            name='personal',
            table='Personal',
        ),
        migrations.AlterModelTable(
            name='registro',
            table='Registro',
        ),
        migrations.AlterModelTable(
            name='servicio',
            table='Servicio',
        ),
        migrations.AlterModelTable(
            name='serviciofactura',
            table='Serviciofactura',
        ),
        migrations.AlterModelTable(
            name='serviciooperativo',
            table='ServicioOperativo',
        ),
    ]
